services:
  mysql:
    image: 'mysql:latest'
    container_name: my-mysql
    environment:
      - 'MYSQL_DATABASE=foodies_management'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
      - 'MYSQL_PASSWORD=secret'
    ports:
      - '3306'
  redis:
    image: 'redis:latest'
    ports:
      - '6379'
